config/routes.rb
Rails.application.routes.draw do

resources :articles do
  resources :comments
end

root 'welcome#index'
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 3}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'You screwed up...now fix it.'
    end
  end

  def destroy
      @article = Article.find(params[:id])
      @article.destroy

      redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        Your <%= pluralize(@article.errors.count, "error") %> screwed up this article...
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :'Bad ass title' %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :'Bad ass text' %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Fix your mistakes you N00B</h1>
<%= render 'form' %>
<%= link_to 'Back that thing up brah', articles_url %>

app/views/articles/index.html.erb
<h1>Listing Bad Ass Articles Here</h1>

<%= link_to 'Start something super cool', new_article_path %>
<p> <p>
<table>
  <tr>
    <th>Bad Ass Title</th>
    <th>Bad Ass Text</th>
    <th colspan="2"></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show me that bad ass article', article_path(article) %></td>
      <td><%= link_to 'You screwed up...now fix it', edit_article_path(article) %></td>
      <td>
        <%= link_to "Get this out of my site", article_path(article),
          method: :delete,
          data: { confirm: 'You sure bro?' }
        %>
      </td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>Shutup and type</h1>
<%= render 'form' %>
<%= link_to 'btfo this article bro', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Bad Ass Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Bad Ass Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment snowflake?</h2>
<%= render 'comments/form' %>

<%=link_to 'You screwed up...now fix it', edit_article_path(@article) %> |
<%=link_to 'I am going home this article is lame', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Snowflake:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Dribble:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy this dribble', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :'snowflake' %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :'useless dribble' %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="container-fluid">
    <header>
      <nav class="navbar navbar-fixed-top navbar-inverse">
        <div class="container-fluid">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to 'Go back to scrub welcome page', controller: 'welcome' %>
          </li>
        </ul>
        </div>
      </nav>
    </header>

    <div class="main">
      <%= yield %>
    </div>

    <div class="row">
      <div class="col-sm-12 bg-green">
        <%= image_tag('disney/disney-everest.jpg', class: 'img-responsive center-block') %>
      </div>
    </div>

  </body>

</html>

app/views/welcome/index.html.erb
<div class="center jumbotron">
  <h1>Sup Scrubs</h1>
  <p>
    David, this is the time: <%= Time.now %>
  </p>
  <p> </p>
  <p>Now go be awesome</p>
  <p> </p>
  <%= link_to 'Visit my blog or you suck', articles_path %>
</div>